### ISSUE TITLE
Config files updating

### ISSUE THREAD

**Issue by AEK-BKF** [svenluijten/file-config#4]
Hi again,
Can we use this package or edit it to allow us updating config files.php ?
Il would be better :)
Thanks

**Comment by svenluijten** [comment]
Honestly I don't see much use in using PHP as a persistent config store, but you can write your own pretty easily: 

```php
<?php

use Sven\FileConfig\Stores\Store;
use Sven\FileConfig\File;

class PhpConfig implements Store
{
    public function __construct(File $file)
    {
        $this->file = $file;
    }

    public function get($key)
    {
        // implementation
    }

    public function set($key, $value)
    {
        // implementation
    }

    public function delete($key)
    {
        // implementation
    }
}
```

Then you can use like you would normally: 

```php
$file = new \Sven\FileConfig\File('/path/to/config.php');

$config = new PhpConfig($file);

$config->set('foo', 'bar'); // true
$config->get('foo'); // 'bar'
$config->delete('foo'); // true
```

**Comment by AEK-BKF** [comment]
Thanks for quick reply,
I tried your suggestion but I got this error : 

> Parse error: syntax error, unexpected '='
> in File.php (line 25)

**Comment by svenluijten** [comment]
It looks like you're running the code with an older version of PHP. This package requires PHP 7.1 oor higher.

**Comment by AEK-BKF** [comment]
my php version :

PHP 7.2.3-1+ubuntu16.04

**Comment by svenluijten** [comment]
I think you're not running the code with that version 🙂 The tests pass fine on PHP 7.1, both on my machine locally and on CircleCI. Double-check to make sure your (web)server is using that version of PHP as well.
